# Generated by Django 5.1.2 on 2024-10-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todomodel1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoModel1',
        ),
    ]
